#ifndef EMERGENCYCENTRELIB_GLOBAL_H
#define EMERGENCYCENTRELIB_GLOBAL_H

#include <QtCore/qglobal.h>


#if defined(EMERGENCYCENTRELIB_LIBRARY)
#  define EMERGENCYCENTRELIB_EXPORT Q_DECL_EXPORT
#else
#  define EMERGENCYCENTRELIB_EXPORT Q_DECL_IMPORT
#endif

#endif // EMERGENCYCENTRELIB_GLOBAL_H
