#ifndef EMERGENCYCENTRELIBRARY_GLOBAL_H
#define EMERGENCYCENTRELIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EMERGENCYCENTRELIBRARY_LIBRARY)
#  define EMERGENCYCENTRELIBRARY_EXPORT Q_DECL_EXPORT
#else
#  define EMERGENCYCENTRELIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // EMERGENCYCENTRELIBRARY_GLOBAL_H
